[package]
name = "bob"
version = "0.1.0"
authors = ["tehforsch <Tonipeter92@googlemail.com>"]
edition = "2018"

[features]
bwfor = []

[dependencies]
# plotters = "0.3"
regex = "1"
clap = "3.0.0-beta.2"
anyhow = "1.0.13"
serde = {version = "1.0.117", features=["derive"]}
serde_derive = {version = "1.0.117"}
serde_yaml = {version = "0.8"}
itertools = "0.9.0"
uom = {version = "0.30.0", features=["use_serde"]}
strfmt = "0.1.6"
hdf5 = "0.7.0"
hdf5-sys = {version = "0.7.0", features=["static"]}
ndarray = { version= "0.13", features=["serde-1"] }
num-traits = "0.2"
ordered-float = "2.0"
csv = "1.1"

[dev-dependencies]
tempdir = "0.3.7"
walkdir = "2.0.1"
dissimilar = "1.0"
