raxiom_path:  "~/projects/raxiom/"
raxiom_build_path:  "/run/media/extHdd/.cargo-target/release/examples"
default_systype: "Manjaro"
bob_path: "~/.cargo/bin/bob"
system_config:
    max_num_cores: 6
    max_num_cores_per_node: 6
    partitions:
      - - 0
        - ""
job_file_run_command: "bash"
job_file_template: |
    #!/bin/bash
    {additionalCommands}
    {runProgram} -n {numCores} {executableName} {runParams} 1> >(tee {logFile} ) 2> >(tee stderr.log )
