subsweep_path:  "~/projects/subsweep/"
subsweep_build_path:  "/run/media/extHdd/.cargo-target/release"
default_systype: "Manjaro"
bob_path: "~/.cargo/bin/bob"
system_config:
    max_num_cores: 6
    max_num_cores_per_node: 6
    partitions:
      - - 0
        - ""
job_file_run_command: "bash"
job_file_template: |
    #!/bin/bash
    {run_program} -n {num_cores} ../{executable_name} {param_file} {run_params} 1> >(tee {log_file} ) 2> >(tee stderr.log )
